# Generated by Django 2.2.5 on 2020-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='pend_side',
            field=models.CharField(blank=True, choices=[('a', 'Antel'), ('e', 'Ericsson')], default='a', max_length=1, verbose_name='Responsable de contestar'),
        ),
    ]
