# Generated by Django 2.2.5 on 2020-04-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='cs_date',
            field=models.DateField(null=True, verbose_name='Fecha CS'),
        ),
    ]
