# Generated by Django 2.2.5 on 2020-04-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200420_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksheet',
            options={'ordering': ['cs_date']},
        ),
    ]
