# Generated by Django 2.2.5 on 2020-04-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200410_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='ca_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha CA'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='claim_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha reclamo pendientes'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='pendings_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha SA'),
        ),
    ]
