# Generated by Django 2.2.5 on 2020-04-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200411_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='closed',
            field=models.CharField(blank=True, choices=[('s', 'Si'), ('n', 'No')], default='n', max_length=1, verbose_name='Obra cerrada'),
        ),
    ]
