# Generated by Django 2.2.5 on 2020-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200420_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksheet',
            options={'ordering': ['-cs_date']},
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='cs_pics_link',
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='ca_pics_link',
            field=models.CharField(blank=True, default='n', max_length=1, null=True, verbose_name='Fotos para servidor Antel'),
        ),
    ]
