# Generated by Django 2.2.5 on 2020-04-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20200421_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='ca_pics_link',
            field=models.CharField(blank=True, choices=[('s', 'Si'), ('n', 'No')], default='', max_length=1, verbose_name='Fotos para servidor de Antel'),
        ),
    ]
